
* Script file
local python_script "path/to/main.py"

********************************************************************************
* Parameters you'll want to change when requesting a new data set
* Full filepaths please
********************************************************************************
* The list of fields you're requesting
local field_list "path/to/fields.txt"

* The name of the desired output data file
* If there are more than max_cols columns of data, it will be split by categories into separate files
local out_file "path/to/output.dta"

* The name of the Stata do-file that will be automatically generated and run to format the data
* (like the one produced by ukbconv)
local out_do "path/to/helper.do"

********************************************************************************
* Parameters you only need to change when the data gets refreshed
* Full filepaths please
********************************************************************************
* You may want to trial and error this a bit to work out how many cols can be held in memory - and it may vary by data type
local max_cols 1500

* Name of the required version of database
local db_name "path/to/ukb_data.db"

* Table name in database
local tblname "ukbXXXXX"

* The paths to the .do and .dct files generated by ukbconv
local do_file "path/to/ukbXXXXX.do"
local dct_file "path/to/ukbXXXXX.dct"

********************************************************************************
* And actually run the script
* The order of the arguments **does matter**
********************************************************************************

python script "`python_script'", args("`field_list'" "`out_file'" "`out_do'" `max_cols' "`db_name'" "`tblname'" "`do_file'" "`dct_file'")

********************************************************************************
* If the output filename you supplied already exists IT WILL BE OVERWRITTEN
********************************************************************************

use "`out_file'"
