data:
 database: "K:/TEU/UKB33952_Data/Data_Downloads/V7_database_duckdb0.7.1/ukb_v7.db"
cleaning:
 renaming: "K:/TEU/UKB33952_Data/Data_Dictionary/Renaming_List_UPDATE_Sep2023_TEU.csv"
 withdrawals: "K:/TEU/UKB33952_Data/Data_Downloads/Withdrawals/w33952_2023-04-25.csv"
 hierarchy: "r/catbrowse.csv"
 ukb_fields: "r/UKB_fields.csv"
