data:
 database: "K:/TEU/UKB33952_Data/Data_Downloads/V6_database_duckdb0.6.2/ukb_v6.db"
cleaning:
 renaming: "K:/TEU/UKB33952_Data/Data_Dictionary/Renaming_List_UPDATE_Sep2021_TEU.csv"
 withdrawals: "K:/TEU/UKB33952_Data/Data_Downloads/Withdrawals/w33952_20220222.csv"
 hierarchy: "r/catbrowse.csv"
 ukb_fields: "r/UKB_fields.csv"
